import { store, kpis, issues, salesTrend, salesTrendLast, inventory, staffing, connections, defaultAgentMessages } from './data/demo.js';
import { agentPlan, generatePurchaseDraft } from './lib/engine.js';

const state = {
  page: 'home',
  agentMessages: [...defaultAgentMessages],
  selectedScenario: 'recommended',
};

const navItems = [
  ['home','⌂','홈'], ['assistant','✦','AI 비서'], ['sales','▥','매출 분석'], ['inventory','◫','재고 관리'], ['staffing','♧','근무 관리'], ['menu','☕','메뉴 관리'], ['marketing','✎','마케팅'], ['connections','↔','데이터 연결']
];

function currency(n){ return `${n.toLocaleString()}원`; }
function layout(content){
  const side = navItems.map(([id,icon,label])=>`<button data-nav="${id}" class="${state.page===id?'active':''}"><span>${icon}</span>${label}</button>`).join('');
  const mobile = [['home','⌂','홈'],['assistant','✦','AI 비서'],['inventory','◫','재고'],['staffing','♧','근무'],['connections','•••','더보기']].map(([id,icon,label])=>`<button data-nav="${id}" class="${state.page===id?'active':''}"><span>${icon}</span>${label}</button>`).join('');
  return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">☕</div>CafeOps</div><nav class="nav">${side}</nav></aside><main class="main">${content}</main><nav class="mobile-nav">${mobile}</nav></div>`;
}
function header(title,subtitle='오늘도 좋은 하루 되세요. AI가 매장 상황을 먼저 점검했어요.'){
 return `<div class="topbar"><div><div class="eyebrow">${store.name}</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="weather"><div style="font-size:26px">🌧️</div><div class="weather-copy"><div>${store.today}</div><small>${store.weather.label} · 강수확률 ${store.weather.rainProbability}%</small></div><strong>${store.weather.temp}°</strong></div></div>`
}
function kpiGrid(){ return `<section class="grid-kpi">${kpis.map(k=>`<div class="card kpi"><div class="kpi-label">${k.label}</div><div class="kpi-value">${k.value}</div><div class="kpi-change ${k.tone}">${k.change}</div></div>`).join('')}</section>`; }
function trendChart(){
 const max = Math.max(...salesTrend,...salesTrendLast);
 const pts = (arr)=>arr.map((v,i)=>`${(i/(arr.length-1))*100},${100-(v/max)*84}`).join(' ');
 return `<div class="chart"><div class="chart-line"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${pts(salesTrendLast)}" fill="none" stroke="#cdb9a6" stroke-width="2"/><polyline points="${pts(salesTrend)}" fill="none" stroke="#4a372f" stroke-width="2.7"/></svg></div></div><div class="legend"><span><i class="dot light"></i>지난주</span><span><i class="dot"></i>이번주(예측)</span></div>`;
}
function home(){ return layout(`${header('안녕하세요, 사장님! 👋')}${kpiGrid()}<div class="two-col"><section class="card section-card"><div class="section-title"><h2>AI가 발견한 오늘의 주요 이슈</h2><span class="badge">자동 감지</span></div><div class="issue-list">${issues.map((x,i)=>`<div class="issue"><div class="issue-icon">${i+1}</div><div><strong>${x.title}</strong><small>${x.subtitle}</small></div><button class="btn" data-nav="${x.type==='inventory'?'inventory':x.type==='staffing'?'staffing':'sales'}">${x.action} →</button></div>`).join('')}</div></section><section class="card section-card"><div class="section-title"><h2>예상 매출 추이</h2><span class="badge">비 예보 반영</span></div>${trendChart()}</section></div>`); }
function inventoryPage(){
 const s = inventory.scenarios;
 return layout(`${header('재고 관리','판매 기록과 레시피를 기반으로 재고 소진 시점과 발주 대안을 계산합니다.')}<div class="page-grid"><section class="card section-card"><div class="section-title"><h2>🍓 ${inventory.ingredient}</h2><span class="badge warn">내일 소진 예상</span></div><div class="metric-row"><div class="metric">현재 재고<div class="value">${inventory.currentQty}${inventory.unit}</div></div><div class="metric">최근 평균 사용<div class="value">${inventory.avgDailyUse}${inventory.unit}/일</div></div><div class="metric">주말 수요 변화<div class="value up">+${Math.round(inventory.demandDelta*100)}%</div></div><div class="metric">예상 소진<div class="value" style="font-size:15px">${inventory.expectedStockout}</div></div></div><div class="section-title" style="margin-top:22px"><h2>발주 시나리오 비교</h2><span class="badge">비용·품절·폐기 균형</span></div><div class="scenario-grid">${s.map(x=>`<div class="scenario ${state.selectedScenario===x.id?'recommended':''}">${x.recommended?'<span class="recommend-tag">AI 권장</span>':''}<h3>${x.label}</h3><div class="qty">${x.qty}kg</div><dl><dt>품절 위험</dt><dd>${x.stockoutRisk}%</dd><dt>폐기 위험</dt><dd>${x.wasteRisk}%</dd><dt>예상 비용</dt><dd>${currency(x.cost)}</dd></dl><button class="btn ${state.selectedScenario===x.id?'primary':''}" data-scenario="${x.id}">${state.selectedScenario===x.id?'선택됨':'선택'}</button></div>`).join('')}</div></section><aside class="card section-card"><div class="section-title"><h2>추천 근거</h2><span class="badge">설명 가능</span></div><div class="callout"><strong>딸기 8kg 발주 권장</strong><br/>현재고 6.2kg, 비 예보 반영 후 주말 수요 +8%, 레시피 기준 원재료 사용량을 함께 계산했습니다.</div><div style="height:12px"></div><button class="btn primary" style="width:100%" id="approvePurchase">선택한 발주안 승인</button><button class="btn" style="width:100%;margin-top:8px" data-nav="assistant">다른 목표로 다시 계산</button></aside></div>`);
}
function staffingPage(){
 return layout(`${header('근무 관리','예상 주문량과 직원 가능시간을 결합해 서비스 수준을 지키는 최소 인력을 제안합니다.')}<div class="page-grid"><section class="card section-card"><div class="section-title"><h2>${staffing.date} 시간대별 권장 인원</h2><span class="badge">수요 예측 기반</span></div><table class="schedule-table"><thead><tr><th>시간대</th><th>예상 주문</th><th>현재</th><th>권장</th><th>변화</th></tr></thead><tbody>${staffing.slots.map(s=>`<tr class="${s.recommended>s.current?'warning':''}"><td data-label="시간대">${s.time}</td><td data-label="예상 주문">${s.orders}건</td><td data-label="현재">${s.current}명</td><td data-label="권장"><strong>${s.recommended}명</strong></td><td data-label="변화" class="${s.recommended>s.current?'warn':''}">${s.recommended>s.current?`+${s.recommended-s.current}명`:'유지'}</td></tr>`).join('')}</tbody></table><button class="btn primary" id="generateSchedule">근무표 자동 생성</button></section><aside class="card section-card"><div class="section-title"><h2>등록 직원</h2><span class="badge">${staffing.employees.length}명</span></div>${staffing.employees.map(e=>`<div class="issue" style="grid-template-columns:1fr auto;margin-bottom:7px"><div><strong>${e.name}</strong><small>${e.available}</small></div><strong>${e.wage.toLocaleString()}원/h</strong></div>`).join('')}</aside></div>`);
}
function connectionsPage(){ return layout(`${header('데이터 연결','새로운 기록 업무를 만들기보다, 이미 쌓이는 데이터를 연결합니다.')}<div class="onboarding-steps">${[['POS 연결','주문·매출 자동 수집'],['매장 정보','주소·영업시간'],['메뉴/레시피','최초 1회 등록'],['직원 정보','가능시간·시급'],['AI 분석 시작','데이터 학습·제안']].map((s,i)=>`<div class="step"><div class="num">${i+1}</div><strong>${s[0]}</strong><small>${s[1]}</small></div>`).join('')}</div><section class="card section-card"><div class="section-title"><h2>현재 연결 상태</h2><span class="badge">데모 모드</span></div><div class="connection-list">${connections.map(c=>`<div class="connection"><div class="conn-icon">${c.automatic?'↻':'＋'}</div><div><strong>${c.title}</strong><small style="display:block;color:var(--muted);margin-top:4px">${c.description}</small></div><div class="status">${c.status}</div></div>`).join('')}</div><div class="callout" style="margin-top:14px"><strong>데이터 원칙</strong><br/>POS 원본은 변경하지 않고 분석에 필요한 주문·결제·상품 정보만 읽습니다. 실제 API가 없는 환경에서는 동일한 스키마의 CSV와 데모 어댑터가 동작합니다.</div></section>`); }
function assistantPage(){ return layout(`${header('AI 운영 비서','질문을 이해하고 필요한 분석 도구를 호출해 근거가 있는 운영안을 만듭니다.')}<section class="card agent-panel"><div class="agent-head"><div><strong>☕ CafeOps Agent</strong><div class="eyebrow" style="margin-top:4px">계산은 전문 도구, 설명은 AI</div></div><span class="badge">DEMO</span></div><div class="agent-messages" id="messages">${renderMessages()}</div><form class="agent-input" id="agentForm"><input id="agentInput" autocomplete="off" placeholder="예: 이번 토요일 비 오는데 운영 어떻게 해야 해?"/><button class="btn primary">전송</button></form></section>`); }
function renderMessages(){ return state.agentMessages.map(m=>`<div class="bubble ${m.role}">${m.text}</div>${m.tools?.length?`<div class="tool-row">${m.tools.map(t=>`<span class="tool-chip">✓ ${t}</span>`).join('')}</div>`:''}${m.cards?.length?`<div class="agent-result-grid">${m.cards.map(c=>`<div class="agent-result"><strong>${c.title}: ${c.value}</strong><small>${c.detail}</small></div>`).join('')}</div>`:''}`).join(''); }
function salesPage(){ return layout(`${header('매출 분석','수요 변화의 패턴을 찾아 실행 가능한 대응까지 연결합니다.')}<div class="two-col"><section class="card section-card"><div class="section-title"><h2>카페라떼 판매 변화</h2><span class="badge down">전주 대비 -18%</span></div>${trendChart()}<div class="callout" style="margin-top:14px"><strong>관찰된 패턴</strong><br/>14~17시 라떼 판매가 가장 크게 감소했고, 같은 시간대 아이스티 판매는 +28% 증가했습니다. 평균 기온 상승과 함께 차가운 음료로 수요가 이동한 패턴이 보이지만, 인과관계로 단정하지 않습니다.</div></section><aside class="card section-card"><div class="section-title"><h2>추천 실행안</h2><span class="badge">초안</span></div><div class="issue" style="grid-template-columns:32px 1fr"><div class="issue-icon">1</div><div><strong>라떼 + 디저트 세트 프로모션</strong><small>오후 14~17시 한정 · 남는 딸기 재고 소진과 연계</small></div></div><button class="btn primary" style="width:100%;margin-top:12px" id="promoBtn">홍보문 자동 생성</button></aside></div>`); }
function placeholder(title){ return layout(`${header(title,'이 기능은 P1 확장 영역입니다. 핵심 데모는 홈·AI 비서·재고·근무·데이터 연결에서 확인할 수 있습니다.')}<div class="card section-card"><div class="callout"><strong>현재 데모 범위</strong><br/>P0 기능의 계산과 사용자 흐름을 우선 완성했습니다. 이 화면은 동일한 데이터 계약을 사용해 확장할 수 있도록 내비게이션과 상태만 유지합니다.</div></div>`); }
function render(){
  const map={home,assistant:assistantPage,sales:salesPage,inventory:inventoryPage,staffing:staffingPage,connections:connectionsPage,menu:()=>placeholder('메뉴 관리'),marketing:()=>placeholder('마케팅')};
  document.getElementById('app').innerHTML=(map[state.page]||home)(); bind();
}
function toast(text){ const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2600); }
function bind(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{state.page=b.dataset.nav;render();window.scrollTo(0,0)}));
 document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{state.selectedScenario=b.dataset.scenario;render();}));
 document.getElementById('approvePurchase')?.addEventListener('click',()=>{const s=inventory.scenarios.find(x=>x.id===state.selectedScenario);const draft=generatePurchaseDraft(s.qty);toast(`${draft.quantity}kg 발주서 초안을 생성했습니다 · ${currency(draft.total)}`)});
 document.getElementById('generateSchedule')?.addEventListener('click',()=>toast('권장 근무표 초안을 생성했습니다. 실제 적용 전 점주 승인이 필요합니다.'));
 document.getElementById('promoBtn')?.addEventListener('click',()=>toast('홍보문 초안을 생성했습니다: “비 오는 오후, 따뜻한 라떼와 디저트 세트 10% 할인”'));
 const form=document.getElementById('agentForm'); if(form){ form.addEventListener('submit',(e)=>{e.preventDefault();const input=document.getElementById('agentInput');const msg=input.value.trim();if(!msg)return;state.agentMessages.push({role:'user',text:msg});const plan=agentPlan(msg);state.agentMessages.push({role:'assistant',...plan});render();setTimeout(()=>{const el=document.getElementById('messages');if(el)el.scrollTop=el.scrollHeight},0);}); }
}
render();
